use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::paths::{AppPaths, reject_reparse};

pub const MARKER: &str = ":: Generated by Nalias Lite. You may edit the command line.";

pub fn validate_name(name: &str) -> Result<(), &'static str> {
    let mut chars = name.chars();
    let first = chars.next().ok_or("alias names cannot be empty")?;
    if !first.is_ascii_alphabetic() {
        return Err("alias names must start with an ASCII letter");
    }
    if !chars
        .all(|character| character.is_ascii_alphanumeric() || character == '-' || character == '_')
    {
        return Err("alias name contains unsupported characters");
    }
    let lower = name.to_ascii_lowercase();
    let reserved = matches!(
        lower.as_str(),
        "nalias" | "nalias-lite" | "con" | "prn" | "aux" | "nul"
    ) || (lower.len() == 4
        && (lower.starts_with("com") || lower.starts_with("lpt"))
        && matches!(lower.as_bytes()[3], b'1'..=b'9'));
    if reserved {
        return Err("alias name is reserved");
    }
    Ok(())
}

pub fn path(paths: &AppPaths, name: &str) -> Result<PathBuf, &'static str> {
    validate_name(name)?;
    Ok(paths.bin.join(format!("{}.cmd", name.to_ascii_lowercase())))
}

pub fn write(paths: &AppPaths, name: &str, command: &str) -> Result<(), &'static str> {
    let body = format!("@echo off\r\n{MARKER}\r\n{command} %*\r\n");
    atomic_write(&path(paths, name)?, body.as_bytes())
}

pub fn is_generated(path: &Path) -> Result<bool, &'static str> {
    reject_reparse(path)?;
    let bytes = fs::read(path).map_err(|_| "could not read the alias file")?;
    Ok(bytes
        .windows(MARKER.len())
        .any(|window| window == MARKER.as_bytes()))
}

pub fn atomic_write(target: &Path, bytes: &[u8]) -> Result<(), &'static str> {
    if target.exists() {
        reject_reparse(target)?;
    }
    let parent = target.parent().ok_or("alias path has no parent")?;
    reject_reparse(parent)?;
    fs::create_dir_all(parent).map_err(|_| "could not create the alias directory")?;
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let temporary = parent.join(format!(".nalias-lite-{}-{nonce}.tmp", std::process::id()));
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&temporary)
        .map_err(|_| "could not create a temporary alias file")?;
    file.write_all(bytes)
        .map_err(|_| "could not write the alias file")?;
    file.sync_all()
        .map_err(|_| "could not flush the alias file")?;
    drop(file);
    if let Err(error) = replace_file(&temporary, target) {
        let _ = fs::remove_file(&temporary);
        return Err(error);
    }
    Ok(())
}

#[cfg(windows)]
fn replace_file(temporary: &Path, target: &Path) -> Result<(), &'static str> {
    use std::os::windows::ffi::OsStrExt;
    use windows_sys::Win32::Storage::FileSystem::{REPLACEFILE_IGNORE_MERGE_ERRORS, ReplaceFileW};

    if !target.exists() {
        return fs::rename(temporary, target).map_err(|_| "could not install the alias file");
    }
    let target_wide: Vec<u16> = target.as_os_str().encode_wide().chain(Some(0)).collect();
    let temporary_wide: Vec<u16> = temporary.as_os_str().encode_wide().chain(Some(0)).collect();
    // SAFETY: Both buffers are valid, NUL-terminated UTF-16 paths for the call.
    let result = unsafe {
        ReplaceFileW(
            target_wide.as_ptr(),
            temporary_wide.as_ptr(),
            std::ptr::null(),
            REPLACEFILE_IGNORE_MERGE_ERRORS,
            std::ptr::null_mut(),
            std::ptr::null_mut(),
        )
    };
    if result == 0 {
        Err("could not replace the alias file")
    } else {
        Ok(())
    }
}

#[cfg(not(windows))]
fn replace_file(temporary: &Path, target: &Path) -> Result<(), &'static str> {
    if target.exists() {
        fs::remove_file(target).map_err(|_| "could not replace the alias file")?;
    }
    fs::rename(temporary, target).map_err(|_| "could not install the alias file")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_names() {
        assert!(validate_name("git-status_2").is_ok());
        for invalid in ["", "2bad", "../bad", "has space", "nul", "nalias-lite"] {
            assert!(validate_name(invalid).is_err(), "{invalid}");
        }
    }

    #[test]
    fn wrappers_contain_only_marker_command_and_forwarding() {
        let temporary = tempfile_path();
        let paths = AppPaths {
            root: temporary.clone(),
            bin: temporary.join("bin"),
            executable: temporary.join("nalias-lite.exe"),
        };
        paths.ensure_directories().unwrap();
        write(&paths, "gs", "git status").unwrap();
        let body = fs::read_to_string(path(&paths, "gs").unwrap()).unwrap();
        assert_eq!(
            body,
            format!("@echo off\n{MARKER}\ngit status %*\n").replace('\n', "\r\n")
        );
        fs::remove_dir_all(temporary).unwrap();
    }

    fn tempfile_path() -> PathBuf {
        std::env::temp_dir().join(format!(
            "nalias-lite-test-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ))
    }
}
