use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::paths::{AppPaths, reject_reparse};

pub const MARKER: &str = ":: Generated by Nalias Lite. Do not edit manually.";
const COMMAND_PREFIX: &str = ":: command-hex: ";

pub fn validate_name(name: &str) -> Result<(), String> {
    let mut chars = name.chars();
    let first = chars
        .next()
        .ok_or_else(|| "alias names cannot be empty".to_owned())?;
    if !first.is_ascii_alphabetic() {
        return Err("alias names must start with an ASCII letter".to_owned());
    }
    if !chars
        .all(|character| character.is_ascii_alphanumeric() || character == '-' || character == '_')
    {
        return Err(
            "alias names may contain only ASCII letters, digits, hyphens, and underscores"
                .to_owned(),
        );
    }
    let lower = name.to_ascii_lowercase();
    let reserved = matches!(
        lower.as_str(),
        "nalias" | "nalias-lite" | "con" | "prn" | "aux" | "nul"
    ) || (lower.len() == 4
        && (lower.starts_with("com") || lower.starts_with("lpt"))
        && matches!(lower.as_bytes()[3], b'1'..=b'9'));
    if reserved {
        return Err(format!("alias name '{name}' is reserved"));
    }
    Ok(())
}

pub fn path(paths: &AppPaths, name: &str) -> Result<PathBuf, String> {
    validate_name(name)?;
    Ok(paths.bin.join(format!("{}.cmd", name.to_ascii_lowercase())))
}

pub fn write(paths: &AppPaths, name: &str, command: &str) -> Result<(), String> {
    let body = format!(
        "@echo off\r\n{MARKER}\r\n{COMMAND_PREFIX}{}\r\n{command} %*\r\n",
        encode_hex(command.as_bytes())
    );
    atomic_write(&path(paths, name)?, body.as_bytes())
}

pub fn is_generated(path: &Path) -> Result<bool, String> {
    reject_reparse(path)?;
    let bytes =
        fs::read(path).map_err(|error| format!("could not read '{}': {error}", path.display()))?;
    Ok(bytes
        .windows(MARKER.len())
        .any(|window| window == MARKER.as_bytes()))
}

pub fn read_all(paths: &AppPaths) -> Result<Vec<(String, String)>, String> {
    let mut aliases = Vec::new();
    for entry in fs::read_dir(&paths.bin)
        .map_err(|error| format!("could not read '{}': {error}", paths.bin.display()))?
    {
        let path = entry
            .map_err(|error| format!("could not read wrapper entry: {error}"))?
            .path();
        if !path
            .extension()
            .is_some_and(|extension| extension.to_string_lossy().eq_ignore_ascii_case("cmd"))
            || !path.is_file()
            || !is_generated(&path)?
        {
            continue;
        }
        let text = fs::read_to_string(&path)
            .map_err(|error| format!("could not read '{}': {error}", path.display()))?;
        let encoded = text
            .lines()
            .find_map(|line| line.strip_prefix(COMMAND_PREFIX))
            .ok_or_else(|| {
                format!(
                    "managed wrapper '{}' has no command metadata",
                    path.display()
                )
            })?;
        let command = String::from_utf8(decode_hex(encoded)?)
            .map_err(|_| format!("managed wrapper '{}' has invalid UTF-8", path.display()))?;
        let name = path
            .file_stem()
            .ok_or_else(|| format!("wrapper '{}' has no name", path.display()))?
            .to_string_lossy()
            .into_owned();
        aliases.push((name, command));
    }
    Ok(aliases)
}

pub fn atomic_write(target: &Path, bytes: &[u8]) -> Result<(), String> {
    if target.exists() {
        reject_reparse(target)?;
    }
    let parent = target
        .parent()
        .ok_or_else(|| format!("'{}' has no parent directory", target.display()))?;
    reject_reparse(parent)?;
    fs::create_dir_all(parent)
        .map_err(|error| format!("could not create '{}': {error}", parent.display()))?;
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let temporary = parent.join(format!(".nalias-lite-{}-{nonce}.tmp", std::process::id()));
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&temporary)
        .map_err(|error| format!("could not create temporary file: {error}"))?;
    file.write_all(bytes)
        .map_err(|error| format!("could not write temporary file: {error}"))?;
    file.sync_all()
        .map_err(|error| format!("could not flush temporary file: {error}"))?;
    drop(file);
    if let Err(error) = replace_file(&temporary, target) {
        let _ = fs::remove_file(&temporary);
        return Err(error);
    }
    Ok(())
}

#[cfg(windows)]
fn replace_file(temporary: &Path, target: &Path) -> Result<(), String> {
    use std::os::windows::ffi::OsStrExt;
    use windows_sys::Win32::Storage::FileSystem::{REPLACEFILE_IGNORE_MERGE_ERRORS, ReplaceFileW};

    if !target.exists() {
        return fs::rename(temporary, target)
            .map_err(|error| format!("could not install '{}': {error}", target.display()));
    }
    let target_wide: Vec<u16> = target.as_os_str().encode_wide().chain(Some(0)).collect();
    let temporary_wide: Vec<u16> = temporary.as_os_str().encode_wide().chain(Some(0)).collect();
    // SAFETY: Both buffers are valid, NUL-terminated UTF-16 paths for the duration of the call.
    let result = unsafe {
        ReplaceFileW(
            target_wide.as_ptr(),
            temporary_wide.as_ptr(),
            std::ptr::null(),
            REPLACEFILE_IGNORE_MERGE_ERRORS,
            std::ptr::null_mut(),
            std::ptr::null_mut(),
        )
    };
    if result == 0 {
        Err(format!(
            "could not replace '{}': {}",
            target.display(),
            std::io::Error::last_os_error()
        ))
    } else {
        Ok(())
    }
}

#[cfg(not(windows))]
fn replace_file(temporary: &Path, target: &Path) -> Result<(), String> {
    if target.exists() {
        fs::remove_file(target)
            .map_err(|error| format!("could not replace '{}': {error}", target.display()))?;
    }
    fs::rename(temporary, target)
        .map_err(|error| format!("could not install '{}': {error}", target.display()))
}

fn encode_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        encoded.push(HEX[(byte >> 4) as usize] as char);
        encoded.push(HEX[(byte & 0x0f) as usize] as char);
    }
    encoded
}

fn decode_hex(value: &str) -> Result<Vec<u8>, String> {
    if !value.len().is_multiple_of(2) {
        return Err("command metadata has an odd number of hexadecimal digits".to_owned());
    }
    value
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| {
            let high = decode_nibble(pair[0])?;
            let low = decode_nibble(pair[1])?;
            Ok((high << 4) | low)
        })
        .collect()
}

fn decode_nibble(value: u8) -> Result<u8, String> {
    match value {
        b'0'..=b'9' => Ok(value - b'0'),
        b'a'..=b'f' => Ok(value - b'a' + 10),
        b'A'..=b'F' => Ok(value - b'A' + 10),
        _ => Err("command metadata contains invalid hexadecimal data".to_owned()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_names() {
        assert!(validate_name("git-status_2").is_ok());
        for invalid in ["", "2bad", "../bad", "has space", "nul", "nalias-lite"] {
            assert!(validate_name(invalid).is_err(), "{invalid}");
        }
    }

    #[test]
    fn hex_metadata_round_trips_unicode() {
        let command = "echo héllo 世界";
        let encoded = encode_hex(command.as_bytes());
        assert_eq!(
            String::from_utf8(decode_hex(&encoded).unwrap()).unwrap(),
            command
        );
    }

    #[test]
    fn wrappers_are_direct_and_listable() {
        let temporary = tempfile_path();
        let paths = AppPaths {
            root: temporary.clone(),
            bin: temporary.join("bin"),
            executable: temporary.join("nalias-lite.exe"),
        };
        paths.ensure_directories().unwrap();
        write(&paths, "gs", "git status").unwrap();
        let body = fs::read_to_string(path(&paths, "gs").unwrap()).unwrap();
        assert!(body.contains("git status %*"));
        assert!(!body.contains("nalias-lite.exe run"));
        assert_eq!(
            read_all(&paths).unwrap(),
            vec![("gs".to_owned(), "git status".to_owned())]
        );
        fs::remove_dir_all(temporary).unwrap();
    }

    fn tempfile_path() -> PathBuf {
        std::env::temp_dir().join(format!(
            "nalias-lite-test-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ))
    }
}
