use std::fs;
use std::path::{Path, PathBuf};

use crate::alias::validate_name;
use crate::config::{atomic_write, reject_symlink};
use crate::error::{NaliasError, Result};
use crate::paths::AppPaths;

pub const MARKER: &str = ":: Generated by Nalias. Do not edit manually.";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WrapperState {
    Missing,
    Current,
    Mismatched,
}

pub fn wrapper_path(paths: &AppPaths, name: &str) -> Result<PathBuf> {
    validate_name(name)?;
    Ok(paths.bin.join(format!("{name}.cmd")))
}

pub fn expected_contents(paths: &AppPaths, name: &str) -> Result<String> {
    validate_name(name)?;
    let executable = paths.executable.to_string_lossy().replace('%', "%%");
    Ok(format!(
        "@echo off\r\n{MARKER}\r\n\"{executable}\" run {name} %*\r\n"
    ))
}

pub fn state(paths: &AppPaths, name: &str) -> Result<WrapperState> {
    let path = wrapper_path(paths, name)?;
    if !path.exists() {
        return Ok(WrapperState::Missing);
    }
    reject_symlink(&path, "wrapper")?;
    let actual = fs::read(&path).map_err(|e| NaliasError::io("could not read wrapper", e))?;
    if actual == expected_contents(paths, name)?.as_bytes() {
        Ok(WrapperState::Current)
    } else {
        Ok(WrapperState::Mismatched)
    }
}

pub fn write(paths: &AppPaths, name: &str) -> Result<()> {
    reject_symlink(&paths.bin, "wrapper directory")?;
    fs::create_dir_all(&paths.bin)
        .map_err(|e| NaliasError::io("could not create the wrapper directory", e))?;
    let path = wrapper_path(paths, name)?;
    if path.exists() && !is_generated_file(&path)? {
        return Err(NaliasError::Installation(format!(
            "refusing to replace unrelated file '{}'",
            path.display()
        )));
    }
    let contents = expected_contents(paths, name)?;
    atomic_write(&path, contents.as_bytes(), false)
        .map_err(|e| NaliasError::Installation(format!("could not write wrapper: {e}")))
}

pub fn is_generated_file(path: &Path) -> Result<bool> {
    if !path.is_file() {
        return Ok(false);
    }
    reject_symlink(path, "wrapper")?;
    let bytes = fs::read(path).map_err(|e| NaliasError::io("could not inspect wrapper", e))?;
    let marker = MARKER.as_bytes();
    Ok(bytes.windows(marker.len()).any(|window| window == marker))
}

pub fn remove(paths: &AppPaths, name: &str) -> Result<bool> {
    let path = wrapper_path(paths, name)?;
    if !path.exists() {
        return Ok(false);
    }
    reject_symlink(&path, "wrapper")?;
    if !is_generated_file(&path)? {
        return Err(NaliasError::Installation(format!(
            "refusing to remove unrelated file '{}'",
            path.display()
        )));
    }
    fs::remove_file(&path).map_err(|e| NaliasError::io("could not remove wrapper", e))?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_wrapper_is_linked_not_embedded() {
        let paths = AppPaths::from_root(PathBuf::from(r"C:\Users\A B\Nalias"));
        let text = expected_contents(&paths, "gs").unwrap();
        assert!(text.contains(MARKER));
        assert!(text.contains(r#""C:\Users\A B\Nalias\nalias.exe" run gs %*"#));
        assert!(!text.contains("git status"));
    }

    #[test]
    fn marker_detection_ignores_unrelated_files() {
        let temp = tempfile::tempdir().unwrap();
        let generated = temp.path().join("a.cmd");
        let unrelated = temp.path().join("b.cmd");
        fs::write(&generated, format!("@echo off\r\n{MARKER}\r\n")).unwrap();
        fs::write(&unrelated, "@echo off\r\necho mine\r\n").unwrap();
        assert!(is_generated_file(&generated).unwrap());
        assert!(!is_generated_file(&unrelated).unwrap());
    }

    #[test]
    fn writes_and_detects_current_wrapper() {
        let temp = tempfile::tempdir().unwrap();
        let paths = AppPaths::from_root(temp.path().join("home"));
        write(&paths, "gs").unwrap();
        assert_eq!(state(&paths, "gs").unwrap(), WrapperState::Current);
    }
}
